### ISSUE TITLE
Why do you want addSlots in parkingLot when it is already initialized?

### ISSUE THREAD

**Issue by nikesh-devaki** [anomaly2104/lld-parking-lot#2]
https://github.com/anomaly2104/lld-parking-lot/blob/9b7c0eddac11a7772f36aa901f2a8cfc519d0083/src/main/java/com/uditagarwal/service/ParkingLotService.java#L35

**Comment by anomaly2104** [comment]
This addition of slot is not for parking lot actually. It is for the parking strategy. These are 2 separate components right now in the solution.
